name: Deploy to Azure

on:
  push:
    branches:
      - Trial
      - 25-03-26
      - 26-03-26
      - 01-04-26
      - 10-may-2026
      - azure
      - azury

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --production

      - name: Zip artifact for deployment
        run: zip -r release.zip server.js package.json package-lock.json constants/ services/ config.js check_db.js node_modules/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: letsbunk-server
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip
